#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys

echo ""
echo "********************************************************"
echo -e " * OZLinux is up running! [uptime: $(cut -d' ' -f1 /proc/uptime) seconds] *"
echo "********************************************************"

exec /bin/sh
