#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys

echo "****************************************************************"
echo -e "\n * OZLinux is up running! [uptime: $(cut -d' ' -f1 /proc/uptime) seconds]\n"
echo "****************************************************************"

exec /bin/sh
